### ISSUE TITLE
Add authentication token expiration/refresh

### ISSUE THREAD

**Issue by gardusig** [conductor-sdk/conductor-go#26]
Related issue: https://github.com/orkes-io/orkes-conductor/issues/111

Evaluate behavior on invalid credentials:
- Should workers keep polling with invalid token?

**Comment by BirknerAlex** [comment]
Hey,

we're running Conductor behind the https://github.com/oauth2-proxy/oauth2-proxy using Keycloak as OpenID connect provider. Since the JWT tokens are expiring after a certain amount of time (in our case 5 minutes) it would be really awesome if the Conductor client of this SDK has a callback method to fetch / refresh the token before polling the tasks / requesting data from the API. 

Maybe similar like the gRPC go library does it with their PerRPCCredentials interface. 
https://pkg.go.dev/google.golang.org/grpc@v1.52.3/credentials#PerRPCCredentials

Currently there are hacky workarounds needed to bypass the OAuth proxy to keep the worker running for more then 5 minutes.
